# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow uses AWS OIDC Connection for Auth
# AWS Role requires permissions to resources
# You can use the condition key:
#   token.actions.githubusercontent.com:sub to limit access in IAM role.
# https://github.com/aws-actions/configure-aws-credentials#OIDC
# https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

name: AWS example workflow
on:
  workflow_dispatch:

env:
# BUCKET_NAME : "<example-bucket-name>"
  AWS_REGION : "us-east-1"
  
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  TaskLists:
    runs-on: ubuntu-latest
    steps:
      # Auth
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::*******:role/OIDC-GitHub-Role
          role-session-name: oidc-github
          aws-region: ${{ env.AWS_REGION }}
      
      # Grab Runner Date & sts identity
      - name:  Grab Runner Date & sts identity
        run: |
          date
          aws sts get-caller-identity
