name: Curl Test for Actions Endpoints

on:
  workflow_dispatch:

jobs:
  run-curl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runs: [1, 2, 3]
    steps:
    - name: Run curl commands and capture output
      run: |
        echo "### Endpoint Test Results" > /tmp/gh_actions_run_${{ matrix.runs }}.md
        for url in \
          "https://vstsagenttools.blob.core.windows.net/" \
          "https://pipelinesghubeus9.actions.githubusercontent.com" \
          "https://productionresultssa0.blob.core.windows.net/" \
          "https://productionresultssa15.blob.core.windows.net/" \
          "https://pipelinesghubeus.actions.githubusercontent.com" \
          "https://acghubeus0.actions.githubusercontent.com/_apis/health" \
          "https://results-receiver.actions.githubusercontent.com" \
          "https://api.github.com" \
          "https://vstoken.actions.githubusercontent.com/_apis/health" \
          "https://pipelines.actions.githubusercontent.com/_apis/health" \
          "https://actions-results-receiver-production.githubapp.com/health" \
          "https://results-receiver.actions.githubusercontent.com/health"
        do
          # echo "" >> /tmp/gh_actions_run_${{ matrix.runs }}.md
          start_time=$(date +%s%3N)
          curl -s -o /dev/null -I -w "HTTP Code: %{http_code}\n" $url # >> /tmp/gh_actions_run_${{ matrix.runs }}.md
          end_time=$(date +%s%3N)
          elapsed=$((end_time - start_time))
          if [ $? -eq 0 ]; then
            echo "${elapsed} ms - Connection to $url was successful." >> /tmp/gh_actions_run_${{ matrix.runs }}.md
          else
            echo "Connection to $url timed out or failed. Time taken: ${elapsed} ms" >> /tmp/gh_actions_run_${{ matrix.runs }}.md
          fi
        done
      continue-on-error: true

    - name: get_hosts_debug
      id: get_hosts_debug
      run: |
        echo "" >> /tmp/gh_actions_run_${{ matrix.runs }}.md
        echo "### /etc/hosts Debug" >> /tmp/gh_actions_run_${{ matrix.runs }}.md
        sed '/^\s*#/d; /^\s*$/d' /etc/hosts >> /tmp/gh_actions_run_${{ matrix.runs }}.md

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gh_actions_run_${{ matrix.runs }}
        path: /tmp/gh_actions_run_${{ matrix.runs }}.md

  combine-reports:
    runs-on: ubuntu-latest
    needs: run-curl
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: /tmp/artifacts

    - name: Combine reports
      run: |
        mkdir -p /tmp/artifacts/
        echo "### Combined Endpoint Test Results" > /tmp/combined_gh_actions_run.md
        for file in /tmp/artifacts/gh_actions_run*/*
        do
          cat "$file" >> /tmp/combined_gh_actions_run.md
          echo -e "\n\n" >> /tmp/combined_gh_actions_run.md
        done

    - name: Upload Combined Report
      uses: actions/upload-artifact@v4
      with:
        name: combined_gh_actions_run
        path: /tmp/combined_gh_actions_run.md
